[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "discord-bot"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "interactions.py",
    "markdown-to-data>=2.0.1",
    "psycopg[binary]",
    "requests",
]
